# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gahSfXVhprru0HyPzgH3miQIu7SugW-3
"""

import pandas as pd
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
import random as rand
a=[0,0,0,1,1,1,2,2,2,3,3,3]#0=red,1=green,2=blue,3=yellow, 4=wild color
s=[0,6,3,9,1,7,5,2,8,5,6,7]#range 0-9= angka
d=[0,0,1,0,1,1,0,0,1,0,1,0]#0=no have,1=have -> nanti yg botnya pilih yg hasilnya 0 khusus hard
f={'color':a,'attr':s,'have':d}
df=pd.DataFrame(f)
df
target=['color','attr']
left=df[target]
right=df['have']
dtree = DecisionTreeClassifier()
dtree = dtree.fit(left, right)
#for l in range (2):
#  for p in range (17):
#   print(dtree.predict([[l,p]]))
#  print("---")

import pydotplus
import matplotlib.pyplot as plt
import matplotlib.image as pltimg

data = tree.export_graphviz(dtree, out_file=None, feature_names=target)
graph = pydotplus.graph_from_dot_data(data)
graph.write_png('mydecisiontree.png')

img=pltimg.imread('mydecisiontree.png')
imgplot = plt.imshow(img)

plt.show()